# Strategy Configuration
# 전략 설정

strategies:
  trend_following:
    enabled: true
    weight: 0.4  # Portfolio allocation weight
    parameters:
      lookback_period: 20
      entry_threshold: 2.0  # Standard deviations
      exit_threshold: 0.5
      max_position_size: 0.1  # 10% of portfolio

    indicators:
      - name: "sma"
        period: 20
      - name: "bollinger_bands"
        period: 20
        std_dev: 2.0

  mean_reversion:
    enabled: true
    weight: 0.3
    parameters:
      lookback_period: 14
      oversold_threshold: 30
      overbought_threshold: 70
      mean_revert_period: 5
      max_position_size: 0.08

    indicators:
      - name: "rsi"
        period: 14
      - name: "mean_price"
        period: 20

  funding_arbitrage:
    enabled: true
    weight: 0.3
    parameters:
      min_funding_rate: 0.01  # 1%
      max_holding_time: 8  # hours
      funding_threshold: 0.005  # 0.5%
      max_position_size: 0.05

    pairs:
      - "BTC/USDT"
      - "ETH/USDT"

# Risk management per strategy
risk_management:
  global_limits:
    max_daily_loss: 0.02  # 2% of portfolio
    max_drawdown: 0.05    # 5% of portfolio
    max_leverage: 3.0

  position_limits:
    max_single_position: 0.2  # 20% of portfolio
    max_correlation: 0.7      # Maximum correlation between positions

  stop_loss:
    enabled: true
    percentage: 0.03  # 3% stop loss
    trailing: true

  take_profit:
    enabled: true
    percentage: 0.06  # 6% take profit

# Regime detection settings
regime_detection:
  enabled: true
  model: "hmm"  # hmm, garch, combined

  hmm:
    n_states: 3  # Bull, Bear, Sideways
    covariance_type: "full"
    n_iter: 100

  garch:
    p: 1  # GARCH(p,q)
    q: 1
    vol_target: 0.15  # 15% annualized volatility

# Portfolio optimization
portfolio:
  optimization_method: "kelly"  # kelly, mean_variance, risk_parity
  rebalance_frequency: "daily"  # hourly, daily, weekly

  kelly_criteria:
    fraction: 0.25  # Fractional Kelly (25% of full Kelly)
    lookback_period: 252  # Trading days for estimation

  constraints:
    min_weight: 0.0
    max_weight: 0.5
    max_turnover: 0.1  # 10% daily turnover limit